felis/USB_Host_Shield_2.0

- cdcprolific.cpp
- cdcprolific.h
This is the fix for the Issue #109 I posted.
This used to work earlier by uncommenting "#define PL2303_COMPAT" from cdcprolific.h
I just re-added code from one of Oleg Mazurov's old commits (see commit: 3d068a063795505a6b577e31e2955577505f3d4e ) which for some reason was lost during a later merge/pull request (See commit: 3d068a063795505a6b577e31e2955577505f3d4e)
> Fix for PL2303HX chips so that PL2303::SndData() works.

- usbhost.h
Fixed a macro definition which would cause the compiler to try
to compile against an undefined function in the RBL SDK.
> Fixed Compile Error with RedBearLabs nRF51288

- avrpins.h
- settings.h
- usbhost.h
This patch adds support for the Teensy LC.
The spi4teensy lib is not compatibe, so for now this forces the SPI into default SPI lib.
Tested working on a USB host mini 2.0 and a USB host 5v modded to 3v3
Tangential note:
The Teensy LC has lower drive current available on the pins compared with the Teensy 3.x.
This meant that I had to remove the level shifters from the host board completely unlike the 3.x which worked just fine.
> Add Teensy LC support. Note: disables spi4teensy lib. (Barry Carter)

- PS3USB.cpp
- README.md
- avrpins.h
- max_LCD.cpp
- settings.h
- usbhost.h
Should be trivial to add support for other STM32 microcontrollers in the future.
Take a look at the following example: https://github.com/Lauszus/Nucleo_F446RE_USBHost
> Added support for STM32F446 Nucleo board

- hidboot.h
As per your suggestion in https://github.com/felis/USB_Host_Shield_2.0/issues/189, I have added support HIDBoot for easily enabling the Report Protocol.
Description:
"Added flag bRptProtoEnable to HIDBoot() constructor. The flag defaults to false in order to maintain current behavior (Boot Protocol). If flag is the to true, HIDBoot() will enable the Report Protocol. This modification is very useful for communication with HID devices with the full, richer, Report Protocol."
This is my first pull request to the library, your advice is welcome.
> Added support to HIDBoot for easily enabling the Report Protocol

- README.md
- examples/USBH_MIDI/USB_MIDI_converter/USB_MIDI_converter.ino
- examples/USBH_MIDI/USB_MIDI_converter_multi/USB_MIDI_converter_multi.ino
- examples/USBH_MIDI/bidrectional_converter/bidrectional_converter.ino
- examples/USBH_MIDI/eVY1_sample/eVY1_sample.ino
- usbh_midi.cpp
- usbh_midi.h
Update MIDI driver and examples.
2016.04.26 (0.3.1)
* Change the type of the variables from byte to uint8_t.
* Limited support for System Exclusive message on bidirectional_converter example.
* Add MidiSysEx Class for System Exclusive packet data management.
* Improve SysExSend() performance.
* Add SendRawData()
* Update debug messages
> Update MIDI driver v0.3.1

- PS4Parser.cpp
- PSBuzz.cpp
- settings.h
The RedbearLab compiler has a type mismatch for
STLs min() and sizeof. Thus we need to cast the
occurences of sizeof to uint8_t.
> [RedBearLab] Fix type mismatch sizeof to uint8_t

- hidboot.h
With compiler warnings set to "More", and compiling against this library, I see warnings of the form:
hidboot.h:381:21: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
num_of_conf = ((USB_DEVICE_DESCRIPTOR*)buf)->bNumConfigurations;
^
This change addresses those warnings, making issues in my own code easier to notice.
> Address "dereferencing type-punned pointer" warnings.

- PS4USB.h
- confdescparser.h
Use descriptor length in order to advance the buffer when parsing the descriptors.
This caused an issue with the PS4 Slim controller, as the endpoint descriptor was two bytes longer on the PS4 slim controller when reading the audio interface.
I suspect this is due to the fact that the audio interface (USB descriptor type 0x24) it is currently not supported by the library.
This is similar to what is done in the example as well: https://github.com/felis/USB_Host_Shield_2.0/blob/cbea36f76ffa0a0b1f74eb59e7ec845ccba380aa/examples/USB_desc/USB_desc.ino#L241.
Fixes issue #273.
> Fixed bug for PS4 Slim controller via USB

- examples/hub_demo/hub_demo.ino
next_time value is ignored. This expression is always true.
```
hub_demo.ino:99:32: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
if ((millis() - next_time) >= 0L) {
^
```
> Fix missing unsigned comparison.

- .travis.yml
- examples/USBH_MIDI/USBH_MIDI_dump/USBH_MIDI_dump.ino
- examples/USBH_MIDI/USB_MIDI_converter/USB_MIDI_converter.ino
- examples/USBH_MIDI/USB_MIDI_converter_multi/USB_MIDI_converter_multi.ino
- examples/USBH_MIDI/bidirectional_converter/bidirectional_converter.ino
- usbh_midi.cpp
- usbh_midi.h
Update MIDI driver and examples.
2017.02.26 (0.3.2)
- Improve reconnect stability.
- Fix for MIDI out only device support.
- Update SysEx code
- Remove MidiSysEx class
- Add new example USB_MIDI_converter_wSysEx
- Fix typo: the example name was corrected from 'bidrectional_converter' to 'bidirectional_converter'.
- Fix Arduino/Genuino 101 compatibility
> Update MIDI driver v0.3.2

- XBOXONE.cpp
- XBOXONE.h
> Newer Xbox One controllers requires a longer initialisation command

- UsbCore.h
- avrpins.h
Added support for *UNO\*Pro*, by detecting the board in `UsbCore.h` and applying correct pins(given by @Lauszus in #345).
**EDIT:** Don't merge now.
> Added support for HobbyTronic's UNO*Pro upgrade.

- UsbCore.h
Tested with USB Shield: DuinoFun UHS mini v2.0 (Aug. 16, 2014)
> Add SS, INT pins for Sanguino.

- XBOXONE.h
[XAC](https://www.xbox.com/en-US/xbox-one/accessories/controllers/xbox-adaptive-controller) works just like an Xbox One but the PID is new.
> Add PID for Xbox Adaptive Controller

- hidboot.cpp
> 0x13 was returned instead of a carriage return (0x0D or '\r')

- usbhost.h
Should fix the problems.
Also removes duplicate code.
> Fix corruption. NEVER use SPI method transfer on a pointer.

- BTHID.cpp
- BTHID.h
for reports that are sent through the control pipe. This happens for
instance in response to a GET_REPORT.
> Add a ParseBTHIDControlData virtual method similar to ParseBTHIDData,

- XBOXONE.h
Adds the PID for the new Xbox Series S / Series X "core" controllers to the `XBOXONE` wired USB class. Tested and working.
These controllers also include a new 'share' button, which is bit 0x01 of byte 22 in the report. Although since the `uint16_t` button variable is already full I'm not sure how best to add it to the class.
> Add Xbox Core Controller PID

- hidcomposite.cpp
- hiduniversal.cpp
- usbhid.h
If a connected device has more than 3 (maxHidInterfaces) HID interfaces,
which is not unusual with modern keyboards, EndpointXtract() wrote
beyond the hidInterfaces[] array and corrupted bHasReportId, PID + VID.
The same could happen with the epInfo[] array.
Now this is fixed by checking bNumIface/bNumEP before adding new
elements to those arrays.
> HIDUniversal, HIDComposite: Don't overflow hidInterfaces[] or epInfo[]

- examples/USBH_MIDI/bidirectional_converter/bidirectional_converter.ino
Fix for handling MIDI channels in the bidirectional converter example (#586)
> Fix for handling MIDI channels in the bidirectional converter example

- SPP.h
- avrpins.h
- settings.h
- usbhost.h
Added definitions for Adafruit NRF52840 Feather Express based on the existing RBL_NRF51822 variant.
I left portions that apply to the whole NRF52 series under generic #ifdef sections to make adding other NRF52 series boards easier in the future. They should just require their own MAKE_PIN section and `typedef SPi` with board specific SPI pin configuration.
I was hoping to find a clean way to support generic NRF boards, but doing some sort of #define based loop seems like it would just make things hard to follow versus the straight forward but redundant MAKE_PIN section here.
The PS5 controller and USB_desc examples have been tested and seem to work fine with a knock off Duinofun USBmini 2.0 shield (after accounting for the mislabeled pins on this hardware, and cutting the USB VDD trace to …
> Added support for Adafruit NRF52840 Feather Express 

- PS3BT.cpp
- PS3Enums.h
- PS3USB.cpp
- PS4Parser.cpp
- PS4Parser.h
- PS5Parser.cpp
- PS5Parser.h
- PSBuzz.cpp
- PSBuzz.h
- Wii.cpp
- Wii.h
- XBOXOLD.cpp
- XBOXOLD.h
- XBOXONE.cpp
- XBOXONESParser.cpp
- XBOXONESParser.h
- XBOXRECV.cpp
- XBOXUSB.cpp
- controllerEnums.h
- xboxEnums.h
Removes the number values associated with each `ButtonEnum` key so that all button identifiers are unique. This fixes issue #611 and potential future issues with the same problem.
Everywhere that referenced one of the enum values directly has been replaced with the `constexpr` function `ButtonIndex` which returns the previously associated value. Each controller now has its own `getButtonIndex` function which takes a `ButtonEnum` value and returns the relevant index value for that key, or `-1` if the key (or previously equivalent aliases) are not present on that controller.
This adds some overhead due to the function calls and also slightly modifies the public interface, because the numbered equivalents for the enums can no longer be used. All previously associated key aliases such as …
> Make ButtonEnum values unique

- Usb.cpp
SNDFIFO is not cleared when USB::OutTransfer() does not complete successfully.
See also #607 
It seems that we can recover with SNDBC=0 according to the following part of [APPLICATION NOTE 4000](https://www.maximintegrated.com/en/design/technical-documents/app-notes/4/4000.html).
> Programming Single-Buffered Transfers
> -- snip --
>    2. If NAK, go to the next step.
>  6. Reload the first FIFO byte, and relaunch the transfer:
>    1. Write SNDBC = 0, a dummy value to switch the FIFO containing the OUT data back under microcontroller control.
> Recover from OUT-NAK

- README.md
- examples/USBH_MIDI/USBH_MIDI_dump/USBH_MIDI_dump.ino
- examples/USBH_MIDI/USB_MIDI_converter/USB_MIDI_converter.ino
- examples/USBH_MIDI/USB_MIDI_converter_multi/USB_MIDI_converter_multi.ino
- examples/USBH_MIDI/bidirectional_converter/bidirectional_converter.ino
- examples/USBH_MIDI/eVY1_sample/eVY1_sample.ino
- usbh_midi.cpp
- usbh_midi.h
2021.5.9 (0.6.0)
- Change configuration descriptor parser. Supports large descriptors. (Fix #616)
- Fixed an issue when the endpoint size exceeded 64 bytes. (Fix #616)
- Add OnInit() callback
- Add a predefined macro "USBH_MIDI_VERSION"
- Changed the method of deriving the message length
- Refine the examples
> Update MIDI driver v0.6.0

- hidboot.h
This fixes buffer handling in `Poll()` of hidboot.h. #646
`Poll()` can cause buffer overrun in `inTransfer()` becase it uses `maxPktSize` as buffer size without checking.
https://github.com/felis/USB_Host_Shield_2.0/blob/08121e1701908006cd646ad51b8c93cf7fe4ce7a/hidboot.h#L585-L593
> hidboot: Fix buffer size and check maxPacketSize #646

- XBOXOLD.cpp
- XBOXOLD.h
- controllerEnums.h
- examples/Xbox/XBOXOLD/XBOXOLD.ino
- examples/Xbox/XBOXONE/XBOXONE.ino
- examples/Xbox/XBOXONESBT/XBOXONESBT.ino
- examples/Xbox/XBOXRECV/XBOXRECV.ino
- examples/Xbox/XBOXUSB/XBOXUSB.ino
- keywords.txt
This adds `LB/RB` and `LT/RT` enum values for the Xbox controllers, in place of the original `L1/R1` and `L2/R2` keys. These are how Microsoft refers to the controls, and what is molded into the plastic on the Xbox 360 controllers. I've also updated the Xbox examples to swap out the keys and related strings.
While I was modifying the Original Xbox code, I also changed a duplicate reference to the VID/PID check and added support for the "Logitech Cordless Precision" controller.
This change uses the same button index value as before, so it should be backwards compatible with previous versions. The old key values can also still be used without issue.
> Add Xbox Trigger Enums

- PS5BT.h
The sequence counter was from 0x0 to 0xE instead of from 0x0 to 0xF
> Fix the sequence counter in the PS5BT output report

- usbh_midi.cpp
- usbh_midi.h
If the CableNumber(CN) is non-zero, RecvData () responds with the wrong message size.
Changed the method to get MIDI message size in version 0.6.0, but the argument was wrong.
In the first byte of the MIDI Event packet, CN is the upper 4 bits and CIN is the lower 4 bits.
Only the lower 4 bits must be given to getMsgSizeFromCin().
> Fix for non-zero CN issue(#688)

- usbh_midi.cpp
- usbh_midi.h
MIDI Driver v1.0.0
* Add OnRelease() callback.
* The timing for enabling PollEnable has been changed to before the onInit() callback.
* Update vender specific code for Novation.
MIDI Driver celebrates its 10th anniversary. :tada:
> Update MIDI driver v1.0.0

- .github/workflows/main.yml
- README.md
- UsbCore.h
- avrpins.h
This adds support for [MightyCore](https://github.com/MCUdude/MightyCore), an Arduino core for a number of larger 32 I/O AVR microcontrollers.
It has 3 selectable pin mapping configurations for compatibility with some other boards. This change should support all 3, though I've only actually tested the "standard" configuration.
> Add support for MightyCore

- library.json
Fixes Library Manager warning:
Library Manager: Could not parse manifest -> Expecting property name enclosed in double quotes: line 10 column 5 (char 332)
> Removed trailing comma in library.json

- avrpins.h
- usbhost.h
Updated for latest Arduino R4 boards (maxima/wifi).
Tested BT with PS4 and XBox, and wired PS4.  Also ran QC sketches.  All was on the Minima board
> Updated for Arduino Uno R4 maxima and wifi

- README.md
- UsbCore.h
- avrpins.h
- examples/HID/scale/scale_rptparser.cpp
- usbhost.h
Seems to work fine with the `board_qc` example.
> Add support for Seeed XIAO nRF52840 Sense Board

- examples/HID/scale/scale_rptparser.cpp
This patch fixes the following error that happens during the automatic build of the project by github CI by removing the spurious (not visible) invalid char.
src/scale_rptparser.cpp:1:69: error: extended character   is not valid in an identifier
1 | #if defined(ARDUINO_SAM_DUE) || defined(ARDUINO_NRF52840_FEATHER) || defined(ARDUINO_Seeed_XIAO_nRF52840_Sense)
|                                                                     ^
src/scale_rptparser.cpp:1:77: error: missing binary operator before token "("
1 | #if defined(ARDUINO_SAM_DUE) || defined(ARDUINO_NRF52840_FEATHER) || defined(ARDUINO_Seeed_XIAO_nRF52840_Sense)
|                                                                             ^
*** [.pio/build/teensy40/src/scale_rptparser.cpp.o] Error 1
> HID/scale: fix invalid extended char

- Usb.cpp
- XBOXOLD.cpp
- XBOXOLD.h
The current code uses hardcoded endpoints to read/write to original Xbox controllers. This works for controllers like 045e:0289 which uses the same endpoint configuration as the hardcoded one.
But other original Xbox controllers like 045e:0202 do not follow the hardcoded configuration and end up not working (can't read reports from them).
This PR modifies the XBOXOLD code to determine endpoints by reading configuration descriptors as in the XBOXONE, instead of hardcoding them. This makes both kind of controllers work.
On this same PR a patch to properly read the left and right analog hats is included too.
> Add support for 045e:0202 duke xbox controller and fix analog hat readings
