felis/USB_Host_Shield_2.0

.travis.yml
README.md

More details http://docs.platformio.org/en/latest/ci/travis.html
P.S: @felis Please enable https://travis-ci.org for this project. It should look like https://travis-ci.org/ivankravets/USB_Host_Shield_2.0.
Comments are welcome!

Continuous Integration with Travis.CI + PlatformIO

---

BTD.cpp
Usb.cpp
UsbCore.h

Add delay between multiple calls to dispatchpkt inside InTransfer

---

hidboot.h

Created a temp variable for LED state

Possible fix for keyboard LED issue

---

BTD.cpp

This is useful as some Bluetooth dongles have a hub inside
Fixes #187

Print error message if a USB Hub is detected in the BTD class

---

cdcftdi.cpp
cdcftdi.h

As there are a lot of FTDI chips arround with a customized PID, i added the possibility to change the PID to be able to connect to customized FTDI chips.

Add possibility to set a custom FTDI PID

---

PS3BT.cpp
PS3USB.cpp
SPP.h
XBOXRECV.cpp
XBOXUSB.cpp
controllerEnums.h
settings.h

@felis @Lauszus please review.
Had to make some changes to the gaming console classes in order to avoid collisions due to unscoped enums. If you have a better idea let me know.

Make USBH work with new RedBear SDK for nRF51288

---

examples/USBH_MIDI/USBH_MIDI_dump/USBH_MIDI_dump.ino
examples/USBH_MIDI/USB_MIDI_converter/USB_MIDI_converter.ino
examples/USBH_MIDI/USB_MIDI_converter_multi/USB_MIDI_converter_multi.ino
examples/USBH_MIDI/bidrectional_converter/bidrectional_converter.ino
examples/USBH_MIDI/eVY1_sample/eVY1_sample.ino
usbh_midi.cpp
usbh_midi.h

Added MIDI host class driver from https://github.com/YuuichiAkagawa/USBH_MIDI.
I contribute this library and join the UHS2.

Contribute MIDI host class driver

---

README.md

I missed update the readme.
Please merge.

Added info about the MIDI library to the README

---

examples/HID/USBHIDMultimediaKbd/USBHIDMultimediaKbd.ino
hidcomposite.cpp
hidcomposite.h

Not sure this is the cleanest way, please comment.

Add HIDcomposite class and example for multimedia keyboards

---

Wii.cpp

Fixes #234
Also added some debugging code, so this could be detected faster in the future

Keep reading the IR camera as well if an extension disconnects

---

BTD.cpp
BTD.h

Workaround issue with Belkin F8T065bf Bluetooth dongle

---

XBOXONE.cpp
XBOXONE.h

Extract the endpoints from the Xbox One controller

---

.travis.yml
README.md
UsbCore.h
avrpins.h
controllerEnums.h
examples/adk/demokit_20/demokit_20.ino
library.json
usbhost.h

Supersedes #340 and fixes #324

Added support for ESP32

---

.travis.yml
README.md
UsbCore.h
avrpins.h
controllerEnums.h
library.json
usbhost.h

fix #324 
Supported Espressif ESP32.

Add ESP32 pin settings 

---

XBOXONE.cpp
XBOXONE.h
examples/Xbox/XBOXONE/XBOXONE.ino

Added support for rumble effect on Xbox One controllers

---

examples/USBH_MIDI/USBH_MIDI_dump/USBH_MIDI_dump.ino
examples/USBH_MIDI/USB_MIDI_converter/USB_MIDI_converter.ino
examples/USBH_MIDI/USB_MIDI_converter_multi/USB_MIDI_converter_multi.ino
examples/USBH_MIDI/bidirectional_converter/bidirectional_converter.ino
examples/USBH_MIDI/eVY1_sample/eVY1_sample.ino
usbh_midi.cpp
usbh_midi.h

Update MIDI driver v0.4.0
ChangeLog
2018.03.24 (0.4.0)
- Updated the examples using #343 feature.
- Vendor/Device specific setup (workaround for #313)

Update MIDI driver v0.4.0

---

usbh_midi.cpp

Update MIDI driver.  
Fix getDevDescr() issue on some devices. (#563)

Pr usbh midi 050

---

examples/USBH_MIDI/USB_MIDI_converter/USB_MIDI_converter.ino
examples/USBH_MIDI/USB_MIDI_converter_multi/USB_MIDI_converter_multi.ino
examples/USBH_MIDI/bidirectional_converter/bidirectional_converter.ino

PR for #570 
Add Serial.flush() option for MIDI examples.

Add Serial.flush() option for MIDI examples

---

XBOXONE.cpp
XBOXONE.h
examples/Xbox/XBOXONE/XBOXONE.ino

Adds support for the 'share' button on Series S/X controllers.

Xbox One USB Share Button

---

.github/workflows/main.yml
README.md
UsbCore.h
avrpins.h

Add support for MightyCore

---

PS5Trigger.h

this feature didn't work until replaced with correct enum value

Replace wrong trigger EffectType
